### ISSUE TITLE
I build a JPackage with ubuntu amd64 operating system. will it  work on any linux os of the architecture with amd64?

### ISSUE THREAD

**Issue by parasuraam** [beryx-gist/badass-runtime-example-javafx#20]
I build a JPackage with ubuntu amd64 operating system. will it  work on any linux os of the architecture with amd64?

https://www.azul.com/downloads/zulu-community/?os=debian&architecture=x86-64-bit&package=jdk

I download azul jdk then I build my JPackage with ubuntu amd64 os.

![linux jpack](https://user-images.githubusercontent.com/67687893/94654436-b2479200-031a-11eb-8fea-a8d55c5b0d5a.PNG)

will my jpackage work on any linux os with  architecture **amd64** ?

will my JPackage work on all the following linux os with architecture amd64?

![lin list](https://user-images.githubusercontent.com/67687893/94654942-72cd7580-031b-11eb-9a98-31d1b96f6415.PNG)

**Comment by Srijan-Sengupta** [comment]
@parasuraam , if you check the link which you have given, you will find that after changing and trying all options from this:
![Screenshot from 2020-09-30 16-38-10](https://user-images.githubusercontent.com/54442785/94678009-6f49e680-033b-11eb-814d-5993da8ba2df.png)

you will find that the JDK name and the requirement remains the same(may be except alpine linux) and as we know that jpackage gives an copy of the JRE, hence, your Deb or RPM packages must work on those distributions may be except alpine linux.

Though I am not very much sure that why they are providing an another JDK build of OpenJDK, but I knew that as all these are distribution for Linux , Hence, have the same Linux Kernel which executes the Executable Programs.

I suspect that Alpine Linux might be using Linux Kernel with some modifications due to which your Package may work or may not work.
But other available Linux operating will work

**Comment by Srijan-Sengupta** [comment]
Is my explanation correct?
